Registration invitation status
fntechgit/summit-admin pull request #337
Opened 2023-11-28 19:40 UTC by santipalenque

https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3423319&stafilter=NotComplete&fileview=grid

2023-12-02 02:18 UTC, smarcet commented on src/actions/attendee-actions.js
> +        filter.push(`tags==${filters.tags.map(t => t.tag).join('||')}`)
could we use tag id instead ?

2023-12-04 13:09 UTC, santipalenque commented on src/actions/attendee-actions.js
> +        filter.push(`tags==${filters.tags.map(t => t.tag).join('||')}`)
done

2023-12-07 18:40 UTC, smarcet commented on src/actions/attendee-actions.js
> +        filter.push(`tags==${filters.tags.map(t => t.id).join('||')}`)
this should be tags_id not just tags

2023-12-07 18:40 UTC, smarcet requested changes
@santipalenque please review comments

2023-12-07 18:50 UTC, smarcet commented on src/components/forms/attendee-form/attendee-form.js
> +                          allowCreate
we dont need to allow to create here we need to remove **allowCreate**

2023-12-07 18:50 UTC, smarcet commented on package.json
> +    "openstack-uicore-foundation": "4.1.58",
lets update uicore to latest

2023-12-07 20:28 UTC, smarcet commented on src/pages/attendees/summit-attendees-list-page.js
> +                allowCreate
we dont need allow create here

2023-12-07 20:35 UTC, smarcet approved these changes
LGTM

2023-12-07 20:35 UTC, merged