custom email templates selection in selection plan crud
fntechgit/summit-admin pull request #54
Opened 2022-04-05 21:15 UTC by romanetar

ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=2875188&fileview=grid

2022-04-06 15:39 UTC, smarcet commented on src/pages/summits/edit-selection-plan-page.js
> +        this.props.getEmailTemplates();
please dont get all also this is paginating and you are getting the first ones

2022-04-06 15:40 UTC, smarcet requested changes
@romanetar please review comments

2022-04-06 15:40 UTC, smarcet commented on src/components/forms/selection-plan-form.js
> +                                    <Dropdown
please use same control as https://github.com/fntechgit/summit-admin/blob/0af7876e819fa61934cb8acd57d0db38d454c753/src/components/forms/email-flow-event-form.js#L89

2022-04-06 15:40 UTC, smarcet commented on src/components/forms/selection-plan-form.js
> +                                    <Dropdown
please use same control as https://github.com/fntechgit/summit-admin/blob/0af7876e819fa61934cb8acd57d0db38d454c753/src/components/forms/email-flow-event-form.js#L89

2022-04-06 15:40 UTC, smarcet commented on src/components/forms/selection-plan-form.js
> +                                    <Dropdown
please use same control as https://github.com/fntechgit/summit-admin/blob/0af7876e819fa61934cb8acd57d0db38d454c753/src/components/forms/email-flow-event-form.js#L89

2022-04-06 17:02 UTC, romanetar commented on src/components/forms/selection-plan-form.js
> +                                    <Dropdown
done

2022-04-06 17:02 UTC, romanetar commented on src/components/forms/selection-plan-form.js
> +                                    <Dropdown
done

2022-04-06 17:02 UTC, romanetar commented on src/components/forms/selection-plan-form.js
> +                                    <Dropdown
done

2022-04-07 18:49 UTC, smarcet approved these changes
LGTM

2022-04-07 18:49 UTC, merged